# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Antony Polukhin 2016-2018.

image: Visual Studio 2017
configuration: Release
platform: x64

test_script:
    - cmake -DCMAKE_BUILD_TYPE=Release
    - nmake
    - ./cpp_fast.exe

