# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Antony Polukhin 2014-2018.

sudo: false
os: linux

env:
    matrix:
        - CXXFLAGS="-std=c++11 -fsanitize=address,undefined" CXX=g++-7 LD=g++-7
        - CXXFLAGS="-std=c++11" CXX=g++-6
        - CXXFLAGS="-std=c++1y" CXX=g++-7
        - CXXFLAGS="-std=c++14" CXX=g++-6
        - CXXFLAGS="-std=c++11" CXX=clang++
        #- CXXFLAGS="-std=c++11 -stdlib=libc++" LINK_FLAGS="-stdlib=libc++" TOOLSET=clang
        #- CXXFLAGS="-std=c++1y -stdlib=libc++" LINK_FLAGS="-stdlib=libc++" TOOLSET=clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - g++-7
    - clang
    - libc++-dev
    - cmake

script:
    - cmake -DCMAKE_BUILD_TYPE=Release
    - VERBOSE=1 make -j2
    - ./cpp_fast
