# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Antony Polukhin 2014-2018.

sudo: false
language: cpp
compiler:
    - gcc

os:
    - linux

env:
    matrix:
        - CXX_FLAGS="-std=c++11 -fsanitize=address,undefined" LINK_FLAGS="" CXX=g++-7
        - CXX_FLAGS="-std=c++11" LINK_FLAGS="" CXX=g++-6
        - CXX_FLAGS="-std=c++1y" LINK_FLAGS="" CXX=g++-7
        - CXX_FLAGS="-std=c++14" LINK_FLAGS="" CXX=g++-6
        - CXX_FLAGS="-std=c++11" LINK_FLAGS="" TOOLSET=clang++
        #- CXX_FLAGS="-std=c++11 -stdlib=libc++" LINK_FLAGS="-stdlib=libc++" TOOLSET=clang
        #- CXX_FLAGS="-std=c++1y -stdlib=libc++" LINK_FLAGS="-stdlib=libc++" TOOLSET=clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - clang
    - libc++-dev
    - cmake

script:
    - cmake -DCMAKE_BUILD_TYPE=Release
    - VERBOSE=1 make -j2
    - ./cpp_fast
    - make distclean
